In [1]:
import torch
import numpy as np

In [ ]:
#常见指定的张量

#1 创建指定的张量（内容形状都自己指定）
tensor = torch.tensor([[1,2],[12,23]])
print(tensor)

#2 创建指定形状的张量（内容随机）
seed = 42

torch.manual_seed(seed) #设置随机种子，随机随机数不是“真随机”，而是伪随机序列，seed决定“起点”，同一个 seed → 同一串随机数

tensor1 = torch.rand(2,3) #创建一个2行3列的张量，内容随机，均匀分布[0,1)之间

tensor2 = torch.randn(2,3) #创建一个2行3列的张量，内容随机，正态分布

tensor3 = torch.randint(0,10,(2,3)) #创建一个2行3列的张量，内容随机，整数，范围在0到10之间

tensor4 = torch.zeros(2,3) #创建一个2行3列的张量，内容全为0

tensor5 = torch.ones(2,3) #创建一个2行3列的张量，内容全为1

tensor6 = torch.eye(3) #创建一个3行3列的张量，内容为单位矩阵

tensor7 = torch.arange(0,10) #创建一个内容在[0,10)之间，步长为1的一维张量

tensor8 = torch.linspace(0,1,5) #创建一个1行5列的张量，内容为0到1之间的等差数列

tensor9 = torch.empty(2,3) #创建一个2行3列的张量，内容随机，未初始化

tensor10 = torch.full((2,3), fill_value=5) #创建一个2行3列的张量，内容全为5

tensor11 = torch.zeros_like(tensor4) #创建一个与tensor4形状相同的张量，内容全为0

tensor12 = torch.ones_like(tensor5) #创建一个与tensor5形状相同的张量，内容全为1


print(tensor1)
print(tensor2)
print(tensor3)
print(tensor4)
print(tensor5)
print(tensor6)
print(tensor7)
print(tensor8)
print(tensor9)
print(tensor10)
print(tensor11)
print(tensor12)


-----

### 2\. 张量常用属性 (Markdown)

快速查看张量自身携带的元数据信息。

| 属性 | 说明 | 示例 |
|------|------|------|
| `.dtype` | 元素的数据类型 | `torch.float32` |
| `.shape` | 张量各维度大小（元组） | `torch.Size([2, 3])` |
| `.ndim` | 维度数量（秩） | `2` |
| `.device` | 所在设备（CPU/GPU） | `device(type='cuda')` |
| `.requires_grad` | 是否需要记录梯度（叶子节点），进行参数更新 | `True` / `False` |
| `.grad` | 存储梯度值（反向传播后） | `tensor([...])` 或 `None` |
| `.grad_fn` | 创建该张量的运算（非叶子节点） | `<AddBackward0>` |
| `.retain_grad` |是否保留非叶子节点的梯度 |  |

-----


In [155]:
# 张量形状与维度操作

# 查看张量的形状和维度
tensor1 = torch.rand(2,3,4) #创建一个2行3列4维的张量，内容随机

print(tensor1)

print(tensor1.shape) #查看张量的形状
print(tensor1.size()) #查看张量的形状
print(tensor1.ndim) #查看张量的维度

# tensor1.requires_grad = True
print(tensor1.requires_grad) #查看张量是否需要梯度,对于一个普通的张量而言，默认是False

print(tensor1.dtype) #查看张量的数据类型
print(tensor1.device) #查看张量所在的设备

tensor([[[0.5472, 0.0062, 0.9516, 0.0753],
         [0.8860, 0.5832, 0.3376, 0.8090],
         [0.5779, 0.9040, 0.5547, 0.3423]],

        [[0.6343, 0.3644, 0.7104, 0.9464],
         [0.7890, 0.2814, 0.7886, 0.5895],
         [0.7539, 0.1952, 0.0050, 0.3068]]])
torch.Size([2, 3, 4])
torch.Size([2, 3, 4])
3
False
torch.float32
cpu


In [156]:
print(tensor1.flatten(start_dim=1)) #从start_dim开始将张量展平，被展平的维度被合并成一个维度

tensor1 = tensor1.contiguous() #将张量变为连续的内存布局，要求数据连续,不是原地操作，需要重新赋值

print(tensor1.view(2,3,4)) #改变张量的形状，要求新形状的元素数量与原形状相同,要求数据连续

print(tensor1.reshape(2,-1)) #改变张量的形状，要求新形状的元素数量与原形状相同,不要求数据连续,-1表示自动计算维度

tensor1 = tensor1.permute(2,0,1) #改变张量的维度顺序，参数为新的维度顺序,不是原地操作，需要重新赋值

print(tensor1)

tensor2 = torch.randn(1,4,2,1)
tensor2 = tensor2.squeeze() #去掉维度为1的维度，或者dim=None
tensor2 = tensor2.unsqueeze(2) #在指定位置插入一个维度为1的维度，-1表示最后一个维度
print(tensor2.shape)

tensor3 = torch.randint(0,100,(2,3,4))
tensor3 = tensor3.transpose(1,2) #交换指定的两个维度
print(tensor3.shape)

tensor([[0.5472, 0.0062, 0.9516, 0.0753, 0.8860, 0.5832, 0.3376, 0.8090, 0.5779,
         0.9040, 0.5547, 0.3423],
        [0.6343, 0.3644, 0.7104, 0.9464, 0.7890, 0.2814, 0.7886, 0.5895, 0.7539,
         0.1952, 0.0050, 0.3068]])
tensor([[[0.5472, 0.0062, 0.9516, 0.0753],
         [0.8860, 0.5832, 0.3376, 0.8090],
         [0.5779, 0.9040, 0.5547, 0.3423]],

        [[0.6343, 0.3644, 0.7104, 0.9464],
         [0.7890, 0.2814, 0.7886, 0.5895],
         [0.7539, 0.1952, 0.0050, 0.3068]]])
tensor([[0.5472, 0.0062, 0.9516, 0.0753, 0.8860, 0.5832, 0.3376, 0.8090, 0.5779,
         0.9040, 0.5547, 0.3423],
        [0.6343, 0.3644, 0.7104, 0.9464, 0.7890, 0.2814, 0.7886, 0.5895, 0.7539,
         0.1952, 0.0050, 0.3068]])
tensor([[[0.5472, 0.8860, 0.5779],
         [0.6343, 0.7890, 0.7539]],

        [[0.0062, 0.5832, 0.9040],
         [0.3644, 0.2814, 0.1952]],

        [[0.9516, 0.3376, 0.5547],
         [0.7104, 0.7886, 0.0050]],

        [[0.0753, 0.8090, 0.3423],
         [0.9464, 0.5895,

In [157]:
# 拼接与拆分操作
tensor1,tensor2 = torch.rand(2,3), torch.rand(2,3)
tensor3 = torch.cat([tensor1,tensor2], dim=1) #在已有维度上进行拼接
tensor4 = torch.stack([tensor1,tensor2], dim=2) #在新维度上进行拼接
print(tensor3.shape)  
print(tensor4.shape)

tensor5_list = torch.split(tensor3,2,dim=1)#第二个参数代表着每一块的大小，而不是一共拆成了多少块
tensor6_list = torch.split(tensor3,[2,4],dim=1)#高级用法，直接指定块的数量以及每一块的大小
tensor7_list = torch.chunk(tensor3,2,dim=1)#第二个参数代表着一共拆成了多少块，而不是每一块的大小


print(len(tensor5_list))
print(tensor5_list[0].shape)

print(len(tensor6_list))
print(tensor6_list[0].shape)

print(len(tensor7_list))
print(tensor7_list[0].shape)


torch.Size([2, 6])
torch.Size([2, 3, 2])
3
torch.Size([2, 2])
2
torch.Size([2, 2])
2
torch.Size([2, 3])


In [158]:
# 数学运算函数
torch.manual_seed(seed) #设置随机种子，保证每次运行结果相同

tensor1,tensor2 = torch.randint(0,10,(5,5)),torch.randint(0,10,(5,5))

print(tensor1)
print(tensor2)

add = tensor1 + tensor2 # torch.add(tensor1,tensor2)
mul = tensor1 * tensor2 #对应元素相乘，要求形状相同或者满足广播机制 torch.mul(tensor1,tensor2)
matmul = tensor1 @ tensor2 #矩阵乘法，要求满足矩阵乘法的规则,对于一维张量而言，matmaul等价于dot函数 torch.matmul(tensor1,tensor2)

print(add)
print(mul)
print(matmul)

tensor3 = torch.sum(tensor1,dim=1) #dim=0表示对列求和，垂直求和，dim=1表示对行求和，水平求和
tensor4 = torch.sum(tensor1)#对所有元素求和,其他的统计函数也是类似的用法，如torch.mean,torch.max,torch.min等

print(tensor3)
print(tensor4)

tensor([[2, 7, 6, 4, 6],
        [5, 0, 4, 0, 3],
        [8, 4, 0, 4, 1],
        [2, 5, 5, 7, 6],
        [9, 6, 3, 1, 9]])
tensor([[3, 1, 9, 7, 9],
        [2, 0, 5, 9, 3],
        [4, 9, 6, 2, 0],
        [6, 2, 7, 9, 7],
        [3, 3, 4, 3, 7]])
tensor([[ 5,  8, 15, 11, 15],
        [ 7,  0,  9,  9,  6],
        [12, 13,  6,  6,  1],
        [ 8,  7, 12, 16, 13],
        [12,  9,  7,  4, 16]])
tensor([[ 6,  7, 54, 28, 54],
        [10,  0, 20,  0,  9],
        [32, 36,  0,  8,  0],
        [12, 10, 35, 63, 42],
        [27, 18, 12,  3, 63]])
tensor([[ 86,  82, 141, 143, 109],
        [ 40,  50,  81,  52,  66],
        [ 59,  19, 124, 131, 119],
        [ 96,  79, 146, 150, 124],
        [ 84,  65, 172, 159, 169]])
tensor([25, 12, 17, 25, 28])
tensor(107)


In [159]:
#4 设备与数据类型转换
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu') #查看当前可用的设备，优先使用GPU

tensor1 = tensor1.to(torch.float32) #将张量的数据类型转换为float32,不是原地操作，需要重新赋值
print(tensor1.device) #查看张量所在的设备
tensor1 = tensor1.to('cpu') #将张量移动到指定设备上,不是原地操作，需要重新赋值

print(tensor1.device)

cpu
cpu


### 表一：`nn.Module` 的三大核心存储区对比

这是 PyTorch 模型内部管理数据的“三个抽屉”，理解它们的区别是核心考点。

| 属性名称 | 核心定义与作用 | 是否算梯度 (requires\_grad) | 优化器是否更新 | 是否存入 state\_dict | 典型代表 | 如何在代码中注册 (添加) |
| :--- | :--- | :---: | :---: | :---: | :--- | :--- |
| **`parameters`** | **模型参数**：需要通过反向传播去“学习”的权重。 | ✅ **是** (默认) | ✅ **是** | ✅ **是** | 线性层的 `weight` / `bias`、卷积核 | 1. 赋值 `nn.Parameter` 对象<br>2. 赋值 PyTorch 内置层 |
| **`buffers`** | **模型状态/缓存**：不需要算梯度，但属于模型固定状态，需长期保存。 | ❌ **否** (通常) | ❌ **否** | ✅ **是** | BatchNorm 的 `running_mean` (均值) 和方差 | 必须显式调用 `self.register_buffer('名字', tensor)` |
| **`modules`** | **子模块/子网络**：模型中嵌套的其他模型，像搭积木一样。 | - | - | - | `nn.Linear`、`nn.Conv2d`、`nn.Sequential` | 直接将实例化的 `nn.Module` 赋值给 self 的属性 |

-----

### 表二：`nn.Module` 常用成员函数与变量速查

这是日常写训练代码（Training Loop）时最常调用的方法。

| 分类 | 名称 / 方法 | 核心作用与一句话笔记 | 使用场景 / 注意事项 |
| :--- | :--- | :--- | :--- |
| **状态变量** | `training` | 这是一个布尔值（True/False），**标识当前处于训练还是推理模式**。 | 强烈影响 `Dropout` 和 `BatchNorm` 层的行为。 |
| **核心计算** | `forward(x)` | **前向传播逻辑**：定义数据流经网络的计算过程（画计算图）。 | **必须重写**。永远不要直接调 `model.forward(x)`，而是直接调用模型 `model(x)`。 |
| **模式切换** | `train()` | 将模型设置为**训练模式** (`training=True`)。 | 开始训练循环前调用。 |
| **模式切换** | `eval()` | 将模型设置为**评估/推理模式** (`training=False`)。 | **测试或验证前必须调用**，防止 Dropout 扔掉数据。 |
| **设备与类型** | `to(device)` | 将模型参数和 buffers **移动到指定设备** (如 GPU/CPU) 或转换类型。 | 常用：`model.to('cuda:0')` 或 `model.half()` (转半精度)。 |
| **保存与加载** | `state_dict()` | **导出权重字典**：返回包含所有 `parameters` 和 `buffers` 的字典。 | **保存模型最推荐的方法**：`torch.save(model.state_dict(), 'xxx.pth')`。 |
| **保存与加载** | `load_state_dict(dict)` | **导入权重字典**：把保存的字典数据重新加载到模型实例中。 | 模型结构必须与保存时完全一致。 |
| **梯度管理** | `zero_grad()` | **清空历史梯度**：把所有参数的 `.grad` 属性清零或设为 None。 | **反向传播 (`loss.backward()`) 前必须调用**，否则梯度会累加。 |

**💡 笔记小贴士：**
你可以把 `parameters` 想象成你的**存款**（天天盯着，随时变化），`buffers` 想象成你的**房产证**（不天天变，但很重要必须保存），而 `modules` 就是装这些东西的**钱包和保险柜**。

In [ ]:
#5 梯度与计算控制

tensor1 = torch.rand(2,3, requires_grad=True) #创建一个需要梯度的张量

model = torch.nn.Sequential(
    torch.nn.Linear(3,4),
    torch.nn.BatchNorm1d(4),
    torch.nn.ReLU(),
)

citeration = torch.nn.CrossEntropyLoss()

optimizer = torch.optim.SGD(model.parameters(), lr=0.01)

labels = torch.tensor([0,1]) #假设标签

for param in model.buffers():
    print(param)

print(model.modules)#查看模型的参数和缓冲区，参数是可训练的，缓冲区是不可训练的

dict = model.state_dict()#导出权重字典，包含模型的参数和缓冲区，参数是可训练的，缓冲区是不可训练的
print(dict)


tensor([0., 0., 0., 0.])
tensor([1., 1., 1., 1.])
tensor(0)


In [108]:
# 训练以及预测

epochs = 10
for epoch in range(epochs):
    optimizer.zero_grad()
    y_hat = model(tensor1)
    loss = citeration(y_hat,labels) #假设标签
    loss.backward() #反向传播计算梯度，然后释放计算图
    optimizer.step() #更新模型参数，梯度下降

with torch.no_grad(): #在这个上下文管理器中，所有的计算都不会被记录到计算图中，也就是说不会计算梯度，适用于推理阶段或者不需要梯度的计算
    y_hat = model(tensor1)
    print(y_hat)

tensor([[-0.4378, -0.5913],
        [-0.4358, -0.6369]])


**广播** 是 PyTorch、NumPy 等库中的一种机制，允许**不同形状的张量进行逐元素运算**。它会自动将较小的张量“扩展”成与较大张量相同的形状，而不需要显式复制数据。

### 核心规则（从尾部维度开始匹配）

1. **从最后一个维度开始往前比较**。
2. 两个维度满足以下条件之一即可兼容：
   - 相等；
   - 其中一个为 `1`；
   - 其中一个维度不存在（视为 `1`）。
3. 不满足上述条件 → 报错 `RuntimeError: The size of tensor a ... must match ...`

In [ ]:
seed = 42

torch.manual_seed(seed)

tensor1,tensor2 = torch.rand(2,3,4),torch.rand(1,4)

sum_tensor = tensor1 * tensor2

print(sum_tensor)


tensor([[[0.0929, 0.2466, 0.1374, 0.1913],
         [0.0411, 0.1619, 0.0921, 0.1582],
         [0.0991, 0.0359, 0.3353, 0.1183]],

        [[0.0916, 0.1530, 0.2659, 0.0856],
         [0.0933, 0.1547, 0.0957, 0.1251],
         [0.0284, 0.1189, 0.1065, 0.1658]]])


---

# 🧠 PyTorch 计算图速记

## 🔷 1. 计算图的基本结构

* **节点（Node）**：表示数据（Tensor）和计算操作（Op）
* **边（Edge）**：表示数据的流动方向

---

## 🔷 2. 叶子节点与中间节点

* **叶子节点（Leaf）**

  * 用户创建（如 `requires_grad=True`）
  * **梯度会保留在 `.grad` 中**

* **非叶子节点（中间节点）**

  * 由运算产生
  * **默认不保留梯度**
  * 如需保留：使用 `retain_grad()`

---

## 🔷 3. grad_fn

* 表示：**该非叶子节点是通过什么运算得到的**
* 本质：计算图中的一个节点（记录反向传播信息）
* 特点：

  * 叶子节点：`grad_fn = None`
  * 非叶子节点：有 `grad_fn`
* 作用：在反向传播中用于**链式求导**

---

## 🔷 4. 计算图什么时候创建？什么是动态图？

* **创建时机**：forward 过程中边计算边创建
* **动态图**：

  * 每次运行（每个 batch）都会重新构建一张图
  * 运行完即销毁（默认）

---

## 🔷 5. backward 后图和梯度状态

执行：

```python
loss.backward()
```

* **计算图**：默认释放（节省内存）
* **梯度（grad）**：只保留在叶子节点
* **grad_fn**：仍存在，但图结构已不可复用
* 如需保留计算图：`retain_graph=True`

---

## 🔷 6. torch.no_grad()

```python
with torch.no_grad():
```

* 不构建计算图
* 不记录 `grad_fn`
* 不计算梯度
* 等价于：`requires_grad=False`
* 用途：推理阶段（节省显存和计算）
* 同理，当所有参与运算的叶子结点的Tensor 都是 **requires_grad=False**时，也不会创建计算图。

---

## 🔷 7. 前向传播是否需要计算图？

* ❌ 不需要（如果不做反向传播）
* ✔️ 计算图只用于梯度计算
* 👉 推理时应关闭计算图（`no_grad`）

---

# 🔥 总结

👉 **训练：forward 建图 + backward 用图
👉 推理：只 forward，不建图**


In [165]:
w = torch.tensor([1.], requires_grad=True)
x = torch.tensor([2.], requires_grad=True)

a = torch.add(w, x)
# a.retain_grad() #保留中间变量的梯度，默认情况下，只有叶子结点的梯度会被保留，如果需要保留中间变量的梯度，需要调用retain_grad()方法
b = torch.add(w, 1)     # retain_grad()
y = torch.mul(a, b)

y.backward()
print(w.grad)

# 查看叶子结点
print("is_leaf:\n", w.is_leaf, x.is_leaf, a.is_leaf, b.is_leaf, y.is_leaf)
# 查看梯度
print("gradient:\n", w.grad, x.grad, a.grad, b.grad, y.grad)
# 查看 grad_fn
print("grad_fn:\n", w.grad_fn, x.grad_fn, a.grad_fn, b.grad_fn, y.grad_fn)

tensor([5.])
is_leaf:
 True True False False False
gradient:
 tensor([5.]) tensor([2.]) None None None
grad_fn:
 None None <AddBackward0 object at 0x0000025C76F14490> <AddBackward0 object at 0x0000025C76F144F0> <MulBackward0 object at 0x0000025C76F14370>


C:\Users\Lenovo\AppData\Local\Temp\ipykernel_11356\403186475.py:15: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\build\aten\src\ATen/core/TensorBody.h:494.)
  print("gradient:\n", w.grad, x.grad, a.grad, b.grad, y.grad)
